### ISSUE TITLE
error in `get_current_apk_id`

### ISSUE THREAD

**Issue by tmm1** [ugroupmedia/fastlane-plugin-amazon-app-store-submission#11]
>fastlane-plugin-amazon_app_submission-0.3.0/lib/fastlane/plugin/amazon_app_submission/helper/amazon_app_submission_helper.rb:88:in `get_current_apk_id': [!] undefined method `[]' for nil:NilClass (NoMethodError)

https://github.com/ugroupmedia/fastlane-plugin-amazon-app-store-submission/blob/f0566795c798aead559fa7f7454548d7c71163f8/lib/fastlane/plugin/amazon_app_submission/helper/amazon_app_submission_helper.rb#L87-L89

do I need to create an upcoming version in the amazon portal manually first?

**Comment by tmm1** [comment]
I printed the response body and see this:

```
[22:44:14]: The amazon_app_submission plugin is working!
[22:44:14]: Fetching app access token
[22:44:14]: Getting current edit
[22:44:15]: Current edit not found, creating a new edit
[22:44:15]: Get current apk id 
{"Message"=>"Unable to fetch the request scope for uri = /appstore/v1/applications/amzn1.devportal.mobileapp.xxx/edits//apks and verb = GET"}
```

It seems that `edit_id` is blank, so creating a new edit maybe not working?

**Comment by tmm1** [comment]
I had newlines in my client id/secret which was causing this issue.

Nonetheless, I made some improvements to make it more clear what is failing in #12, which showed:

>helper/amazon_app_submission_helper.rb:46:in `create_new_edit': \e[31m[!] {"Message":"Request is not authorized."}\e[0m (RuntimeError)
